Update rhel10_cis_level1

diff --git a/rhel10_cis_level1 b/rhel10_cis_level1
--- a/rhel10_cis_level1
+++ b/rhel10_cis_level1
@@ -1974,38 +1974,38 @@ echo '--------------------------------------'
 echo "5.4.1.6 Ensure all users last password change date is in the past"
 echo "Not implemented... Automatic remediation is not available, in order to avoid any system disruption"
 
-# this needs more testing
-#echo '--------------------------------------'
-#echo "5.3.3.4.1 Prevent Login to Accounts With Empty Password"
-## Remediation is applicable only in certain platforms
-#if rpm --quiet -q kernel; then
-#   if [ -f /usr/bin/authselect ]; then
-#      if ! authselect check; then
-#         echo " authselect integrity check failed. Remediation aborted!"
-#         echo "This remediation could not be applied because an authselect profile was not selected or the selected profile is not intact."
-#         echo "It is not recommended to manually edit the PAM files when authselect tool is available."
-#         echo "In cases where the default authselect profile does not cover a specific demand, a custom authselect profile is recommended."
-#         exit 1
-#      fi
-#      authselect enable-feature without-nullok
-#      authselect apply-changes -b
-#   else
-#      if grep -qP "^\s*auth\s+sufficient\s+pam_unix.so\s.*\bnullok\b" "/etc/pam.d/system-auth"; then
-#         sed -i -E --follow-symlinks "s/(.*auth.*sufficient.*pam_unix.so.*)\bnullok\b=?[[:alnum:]]*(.*)/\1\2/g" "/etc/pam.d/system-auth"
-#      fi
-#      if grep -qP "^\s*password\s+sufficient\s+pam_unix.so\s.*\bnullok\b" "/etc/pam.d/system-auth"; then
-#         sed -i -E --follow-symlinks "s/(.*password.*sufficient.*pam_unix.so.*)\bnullok\b=?[[:alnum:]]*(.*)/\1\2/g" "/etc/pam.d/system-auth"
-#      fi
-#      if grep -qP "^\s*auth\s+sufficient\s+pam_unix.so\s.*\bnullok\b" "/etc/pam.d/password-auth"; then
-#         sed -i -E --follow-symlinks "s/(.*auth.*sufficient.*pam_unix.so.*)\bnullok\b=?[[:alnum:]]*(.*)/\1\2/g" "/etc/pam.d/password-auth"
-#      fi
-#      if grep -qP "^\s*password\s+sufficient\s+pam_unix.so\s.*\bnullok\b" "/etc/pam.d/password-auth"; then
-#         sed -i -E --follow-symlinks "s/(.*password.*sufficient.*pam_unix.so.*)\bnullok\b=?[[:alnum:]]*(.*)/\1\2/g" "/etc/pam.d/password-auth"
-#      fi
-#   fi
-#else
-#    >&2 echo 'Remediation is not applicable, nothing was done'
-#fi
+
+echo '--------------------------------------'
+echo "5.3.2.4.1 Prevent Login to Accounts With Empty Password"
+# Remediation is applicable only in certain platforms
+if rpm --quiet -q kernel; then
+   if [ -f /usr/bin/authselect ]; then
+      if ! authselect check; then
+         echo " authselect integrity check failed. Remediation aborted!"
+         echo "This remediation could not be applied because an authselect profile was not selected or the selected profile is not intact."
+         echo "It is not recommended to manually edit the PAM files when authselect tool is available."
+         echo "In cases where the default authselect profile does not cover a specific demand, a custom authselect profile is recommended."
+         exit 1
+      fi
+      authselect enable-feature without-nullok
+      authselect apply-changes -b
+   else
+      if grep -qP "^\s*auth\s+sufficient\s+pam_unix.so\s.*\bnullok\b" "/etc/pam.d/system-auth"; then
+         sed -i -E --follow-symlinks "s/(.*auth.*sufficient.*pam_unix.so.*)\bnullok\b=?[[:alnum:]]*(.*)/\1\2/g" "/etc/pam.d/system-auth"
+      fi
+      if grep -qP "^\s*password\s+sufficient\s+pam_unix.so\s.*\bnullok\b" "/etc/pam.d/system-auth"; then
+         sed -i -E --follow-symlinks "s/(.*password.*sufficient.*pam_unix.so.*)\bnullok\b=?[[:alnum:]]*(.*)/\1\2/g" "/etc/pam.d/system-auth"
+      fi
+      if grep -qP "^\s*auth\s+sufficient\s+pam_unix.so\s.*\bnullok\b" "/etc/pam.d/password-auth"; then
+         sed -i -E --follow-symlinks "s/(.*auth.*sufficient.*pam_unix.so.*)\bnullok\b=?[[:alnum:]]*(.*)/\1\2/g" "/etc/pam.d/password-auth"
+      fi
+      if grep -qP "^\s*password\s+sufficient\s+pam_unix.so\s.*\bnullok\b" "/etc/pam.d/password-auth"; then
+         sed -i -E --follow-symlinks "s/(.*password.*sufficient.*pam_unix.so.*)\bnullok\b=?[[:alnum:]]*(.*)/\1\2/g" "/etc/pam.d/password-auth"
+      fi
+   fi
+else
+    >&2 echo 'Remediation is not applicable, nothing was done'
+fi
 
 
 
