Update rhel10_cis_level1

diff --git a/rhel10_cis_level1 b/rhel10_cis_level1
--- a/rhel10_cis_level1
+++ b/rhel10_cis_level1
@@ -8,6 +8,7 @@
 # 2026-02-26    njeffrey    Add sections for removing kernel modules cramfs jffs2 usb-storage
 # 2026-08-31    njeffrey    Add section 1.2.1.1 install sequoia-sq
 # 2026-08-31    njeffrey    Add section 5.1.6 Implement Custom Crypto Policy Modules for CIS Benchmark
+# 2026-09-30    njeffrey    Add section 3.1.3. Disable Bluetooth service
 
 # Enable debugging
 set -x
@@ -3345,7 +3346,38 @@ fi
 
 
 
-
+echo '--------------------------------------'
+echo 3.1.3 Disable Bluetooth Service
+# Remediation is applicable only in certain platforms
+if rpm --quiet -q kernel-core; then
+   SYSTEMCTL_EXEC='/usr/bin/systemctl'
+   if [[ $("$SYSTEMCTL_EXEC" is-system-running) != "offline" ]]; then
+      "$SYSTEMCTL_EXEC" stop 'bluetooth.service'
+   fi
+   # Disable bluetooth.service only if it is not already disabled/masked
+   if [ "$(systemctl is-enabled bluetooth.service 2>/dev/null)" != "masked" ] && \
+      [ "$(systemctl is-enabled bluetooth.service 2>/dev/null)" != "disabled" ]; then
+      "$SYSTEMCTL_EXEC" disable bluetooth.service
+   fi
+   # Mask bluetooth.service only if it is not already masked
+   if [ "$(systemctl is-enabled bluetooth.service 2>/dev/null)" != "masked" ]; then
+      "$SYSTEMCTL_EXEC" mask bluetooth.service
+   fi
+   #
+   # Disable socket activation if we have a unit file for it
+   if "$SYSTEMCTL_EXEC" -q list-unit-files bluetooth.socket; then
+      if [[ $("$SYSTEMCTL_EXEC" is-system-running) != "offline" ]]; then
+         "$SYSTEMCTL_EXEC" stop 'bluetooth.socket'
+      fi
+      "$SYSTEMCTL_EXEC" mask 'bluetooth.socket'
+   fi
+   # The service may not be running because it has been started and failed,
+   # so let's reset the state so OVAL checks pass.
+   # Service should be 'inactive', not 'failed' after reboot though.
+   "$SYSTEMCTL_EXEC" reset-failed 'bluetooth.service' 2>/dev/null || true
+else
+   >&2 echo 'Remediation is not applicable, nothing was done'
+fi
 
 
 
